### ISSUE TITLE
Fails on 19.04.2022

### ISSUE THREAD

**Issue by boileaum** [p-gerhard/agricas#1]
I've just tried it:

```bash
(.venv) (base) boileau@m-boileau:  [master]  /tmp/agricas$ python --version && date && python agricas.py 
Python 3.9.12
Mar 19 avr 2022 08:15:12 CEST
Traceback (most recent call last):
  File "/private/tmp/agricas/agricas.py", line 140, in <module>
    menu_lst = get_data()
  File "/private/tmp/agricas/agricas.py", line 57, in get_data
    assert date is not None
AssertionError
```

**Comment by p-gerhard** [comment]
Fixed. It was because of some malformed date like "Monday" not followed by a day of the month.
